language: node_js
node_js:
- 10.0.0
cache:
  yarn: true
  directories:
  - node_modules
  - Example/node_modules
branches:
  only:
  - master
  - develop
install:
- yarn global add codecov
- yarn && yarn --cwd Example/
script:
- yarn run test && codecov
