language: node_js
node_js:
- 9.11.1
cache:
  yarn: true
  directories:
  - node_modules
  - Example/node_modules
branches:
  only:
  - master
  - develop
install:
- git fetch --unshallow --all
- yarn global add codecov
- yarn
script:
- yarn run test:prepare && yarn run test && codecov