// flow-typed signature: 7c9659aae42ac319e7274fbcbe92cb38
// flow-typed version: <<STUB>>/react-native-reachability_v1.0.5/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-reachability'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-reachability' {
  declare module.exports: any;
}
